version: '3.8'
services:
  api-gateway:
    image: zeusprogetto/api-gateway
    container_name: api-gateway
    networks:
      - zeus-net
    volumes:
      - /Users/logs/zeus/api-gateway:/logs/local
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/apigatewaydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  zeus-ui:
    image: zeusprogetto/zeus-ui
    container_name: zeus-ui
    networks:
      - zeus-net
    ports:
      - "81:80"
    environment:
      API_URL: http://localhost:8088
#  member-mgmt-service:
#    image: zeusprogetto/member-mgmt-service:latest
#    container_name: member-mgmt-service
#    networks:
#      - zeus-net
#    volumes:
#      - /Users/logs/zeus/member-mgmt-service:/logs/local
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
#      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/membermgmtdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
networks:
  zeus-net:
    name: zeus-net
    driver: bridge